### ISSUE TITLE
Cannot find startAI2U.cmd

### ISSUE THREAD

**Issue by bzhtitude** [technologiescollege/AI2U_server#1]
Bonjour, 

Après dézippage, en lançant tous les serveurs (module serveur), on tombe sur une erreur : 
Cannot find AI2U/startAI2U.cmd

en effet dans le fichier AI2U , le fichier s'appelle startAI.cmd et non startAI2U.cmd
en modifiant le nom, ça fonctionne comme un charme.

Merci pour tout tes logiciels

BZH

**Comment by SebCanet** [comment]
Bonjour,
normalement c'est réglé, merci de tester.
Et j'ai corrigé un bug de fermeture.

**Comment by bzhtitude** [comment]
C'est testé --> OK  ( test uniquement en local pour le moment car je n'ai pas de VM)
